// All available coupons for display and cart use
export const AVAILABLE_COUPONS = [
  {
    code: "FREEDEL",
    type: "free_delivery",
    label: "Free Delivery",
    description: "Get free delivery on your order",
    minOrder: 500,
    discount: null,
    validity: "Valid till 31 Dec 2025",
    terms: "Min order ₹500. Applicable on delivery charges only.",
  },
  {
    code: "SAVE50",
    type: "flat",
    label: "₹50 Off",
    description: "Flat ₹50 off on your order",
    minOrder: 999,
    discount: 50,
    validity: "Valid till 31 Dec 2025",
    terms: "Min order ₹999. One-time use per user.",
  },
  {
    code: "WELCOME100",
    type: "flat",
    label: "₹100 Off",
    description: "Welcome offer - ₹100 off",
    minOrder: 1499,
    discount: 100,
    validity: "Valid till 15 Feb 2026",
    terms: "Min order ₹1499. New users only.",
  },
  {
    code: "FLAT20",
    type: "percent",
    label: "20% Off",
    description: "Upto 20% off on selected items",
    minOrder: 799,
    discount: 20,
    maxDiscount: 500,
    validity: "Valid till 28 Feb 2026",
    terms: "Min order ₹799. Max discount ₹500.",
  },
  {
    code: "BIG500",
    type: "flat",
    label: "₹500 Off",
    description: "Mega savings on orders above ₹2999",
    minOrder: 2999,
    discount: 500,
    validity: "Valid till 10 Mar 2026",
    terms: "Min order ₹2999. Limited period offer.",
  },
];
